# Generated by Django 2.1.15 on 2021-02-09 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='メンバー')),
                ('event_date', models.DateField()),
                ('price', models.PositiveIntegerField()),
                ('is_paid', models.BooleanField(default=False, verbose_name='支払いしたか')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='イベント名')),
            ],
        ),
        migrations.AddField(
            model_name='borrowevent',
            name='event_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='BalanceApp.Event', verbose_name='イベント名'),
        ),
    ]
